# -*- coding: utf-8 -*-
CATS = {
    "missa": {"label": "Santa Missa", "kicker": "uma curiosidade da Santa Missa"},
    "santos": {"label": "Santos", "kicker": "uma curiosidade sobre os santos"},
    "padres": {"label": "Padres", "kicker": "uma curiosidade sobre os padres"},
    "historia": {"label": "História da Igreja", "kicker": "uma curiosidade da história da Igreja"},
    "chosen": {"label": "The Chosen", "kicker": "uma curiosidade sobre a série"},
    "mundo": {"label": "Mundo Católico", "kicker": "uma curiosidade do mundo católico"},
}

POSTS = [
    dict(n=1, cat="missa", hook="Por que a missa se chama “missa”?",
         fact="A palavra vem do latim “Ite, missa est”, dito no fim da celebração — algo como “ide, sois enviados”. A mesma raiz de missão: a missa termina, mas a fé sai pela porta com você.",
         caption="Você sabia que a palavra “missa” é, literalmente, um convite pra sair e viver o que você acabou de celebrar? \U0001F64F\n\nA expressão “Ite, missa est”, dito no fim da celebração, é de onde vem o nome — e tem a mesma raiz de “missão”.\n\nA missa não termina na porta da igreja. Comenta aqui embaixo se você sabia dessa! \U0001F447",
         tags="#missacatolica #catolico #fecatolica #liturgia #igrejacatolica #compendiocatolico #catequese #cristaos",
         photo="Interior de igreja com luz entrando pelos vitrais durante a missa — busque “Catholic mass sunlight” ou “igreja vitral luz” no Unsplash/Wikimedia Commons."),
    dict(n=2, cat="missa", hook="O incenso da missa é mais antigo que o cristianismo",
         fact="Usar incenso no culto vem do Antigo Testamento (Livro do Íxodo) — e o Salmo 141 já comparava a fumaça subindo ao céu com a própria oração do fiel.",
         caption="Aquele perfume de incenso na missa não é só tradição bonita — é um símbolo com mais de 3 mil anos. \U0001F56F️\n\nO Salmo 141 diz: “suba a minha oração como incenso perante vós”. A fumaça sobe, a oração sobe.\n\nSalva esse post pra lembrar da próxima vez que sentir o cheiro na igreja.",
         tags="#incenso #liturgia #missacatolica #catolico #salmos #biblia #fecatolica #tradicaocatolica",
         photo="Turíbulo (incensário) balançando com fumaça — busque “thurible incense censer” no Wikimedia Commons."),
    dict(n=3, cat="missa", hook="Por que o padre levanta a hóstia bem alto?",
         fact="A elevação da hóstia após a consagração começou por volta do século XII — para que os fiéis, que comungavam raramente na época, pudessem ao menos “ver a Deus” com os próprios olhos.",
         caption="Esse gesto que você vê toda missa — o padre erguendo a hóstia bem alto — nasceu de um motivo bem humano. \U0001F446\n\nNa Idade Média, muita gente comungava só uma vez por ano. A elevação surgiu pra que todos pudessem, ao menos, contemplar o momento da consagração.\n\nHoje, mesmo comungando toda semana, vale reaprender a olhar com os mesmos olhos de quem só tinha aquele instante.",
         tags="#eucaristia #santamissa #consagracao #catolico #fecatolica #liturgia #jesuseucaristico",
         photo="Elevação da hóstia/cálice durante a consagração — busque “elevation of the host mass” no Wikimedia Commons."),
    dict(n=4, cat="missa", hook="O sininho da missa tem um motivo prático",
         fact="O sino tocado na consagração surgiu na Idade Média, quando muitas missas eram rezadas em latim, de costas para o povo, em igrejas grandes — o som avisava até quem estava do lado de fora que o momento mais sagrado estava acontecendo.",
         caption="Já reparou no sininho que toca na consagração? Ele existe por um motivo bem prático. \U0001F514\n\nNa Idade Média, com igrejas enormes e missas em latim, o sino avisava a todos — inclusive quem estava fora da igreja — que o momento mais sagrado da missa estava acontecendo.\n\nHoje é tradição. Antes, era o “aviso sonoro” de que Deus estava ali.",
         tags="#missacatolica #tradicaocatolica #historiadaigreja #liturgia #catolico #fecatolica",
         photo="Sacristão/coroinha tocando sino durante a missa, ou close do sino litúrgico — busque “altar bells mass” no Wikimedia Commons."),
    dict(n=5, cat="missa", hook="Existem mais de 20 formas diferentes de rezar a missa católica",
         fact="Além do rito romano (o mais comum no Brasil), a Igreja Católica reconhece ritos como o bizantino, maronita, siro-malabar e armênio — todos plenamente católicos, todos em comunhão com o Papa.",
         caption="“Católico” não é sinônimo de “rito romano” — a Igreja é bem mais diversa do que parece. ⛪\n\nExistem ritos orientais católicos como o bizantino, o maronita e o siro-malabar, com liturgias, cantos e vestes diferentes — mas todos em plena comunhão com Roma.\n\nQual desses você já ouviu falar? Comenta aí.",
         tags="#igrejacatolica #ritooriental #liturgia #catolicismo #fecatolica #historiadaigreja #compendiocatolico",
         photo="Liturgia de rito bizantino católico (iconostase, vestes douradas) — busque “Eastern Catholic Divine Liturgy” no Wikimedia Commons."),

    dict(n=6, cat="santos", hook="Ela nunca saiu do convento — e virou padroeira das missões",
         fact="Santa Teresinha do Menino Jesus viveu e morreu dentro de um convento de clausura na França, sem nunca pisar num país de missão — mesmo assim, é proclamada padroeira universal das missões, ao lado de São Francisco Xavier.",
         caption="Como alguém que nunca saiu de um convento virou padroeira das missões do mundo inteiro? \U0001F30D\n\nSanta Teresinha de Lisieux viveu de portas fechadas — mas dizia que se pudesse, seria missionária em todos os continentes ao mesmo tempo, só de oferecer suas orações.\n\nA missão dela era o “pequeno caminho”: amar em cada gesto simples do dia a dia.",
         tags="#santateresinha #santoscatolicos #catolico #fecatolica #missoes #igrejacatolica",
         photo="Imagem/ícone de Santa Teresinha do Menino Jesus com rosas — busque “Saint Thérèse of Lisieux” no Wikimedia Commons."),
    dict(n=7, cat="santos", hook="Por que São Judas Tadeu é o santo das causas impossíveis?",
         fact="Segundo a tradição, seu nome lembrava demais o de Judas Iscariotes — então quase ninguém o invocava, com medo de confusão. Resultado: ele ficou disponível justamente para os casos que ninguém mais queria assumir, as causas mais difíceis e desesperadas.",
         caption="Existe uma explicação curiosa pra São Judas Tadeu ser o santo das causas impossíveis. \U0001F54A️\n\nComo o nome dele lembrava o de Judas Iscariotes, quase ninguém o invocava — e, com o tempo, ele passou a ser chamado justamente para os pedidos mais difíceis, os que pareciam sem solução.\n\nSe você reza pra ele, comenta aqui embaixo!",
         tags="#saojudastadeu #causasimpossiveis #santoscatolicos #catolico #fecatolica #devocao",
         photo="Imagem/estátua de São Judas Tadeu com a chama sobre a cabeça e medalhão — busque “Saint Jude Thaddeus” no Wikimedia Commons."),
    dict(n=8, cat="santos", hook="O santo que teve um filho fora do casamento antes de virar Doutor da Igreja",
         fact="Antes de se converter, Santo Agostinho viveu anos numa vida bem distante da fé e teve um filho fora do casamento. Sua mãe, Santa Mônica, rezou e chorou por sua conversão durante quase 20 anos.",
         caption="Se você acha que é tarde demais pra mudar de vida, conhece a história de Santo Agostinho? ✝️\n\nAntes de virar um dos maiores nomes da teologia católica, ele viveu longe da fé, teve um filho fora do casamento e resistiu à conversão por anos.\n\nQuem nunca desistiu dele foi a mãe, Santa Mônica — quase 20 anos de oração até aquele “sim”.",
         tags="#santoagostinho #santamonica #conversao #catolico #fecatolica #doutoresdaigreja #historiadaigreja",
         photo="Pintura de Santo Agostinho (Botticelli ou Caravaggio) ou de Santa Mônica — busque “Saint Augustine painting” no Wikimedia Commons."),
    dict(n=9, cat="santos", hook="O primeiro registro histórico das chagas de Cristo num ser humano",
         fact="Em 1224, no Monte Alverne, São Francisco de Assis recebeu os estigmas — as marcas das chagas de Cristo — sendo o primeiro caso conhecido na história da Igreja.",
         caption="São Francisco de Assis é lembrado como o santo dos bichinhos — mas a história dele guarda algo ainda mais impressionante. \U0001F54A️\n\nEm 1224, ele foi a primeira pessoa na história registrada a receber os estigmas: as marcas das cinco chagas de Cristo, em seu próprio corpo.\n\nUma vida de simplicidade radical, marcada literalmente pela paixão de Jesus.",
         tags="#saofrancisco #saofranciscodeassis #estigmas #santoscatolicos #catolico #fecatolica #franciscanos",
         photo="São Francisco recebendo os estigmas (afresco de Giotto na Basílica de Assis) — busque “Giotto Stigmata of Saint Francis” no Wikimedia Commons."),
    dict(n=10, cat="santos", hook="O santo dos millennials catalogou milagres eucarísticos aos 11 anos",
         fact="Carlo Acutis, canonizado como um dos primeiros santos “da era da internet”, começou a montar um site catalogando milagres eucarísticos ao redor do mundo com apenas 11 anos de idade.",
         caption="Aos 11 anos, enquanto a maioria de nós jogava videogame, Carlo Acutis já catalogava milagres eucarísticos num site que ele mesmo programou. \U0001F4BB\U0001F64F\n\nEle morreu aos 15 anos, de leucemia, dizendo: “A Eucaristia é minha autoestrada para o céu”.\n\nO “santo dos millennials” prova que dá pra ser jovem, usar tecnologia e ser santo ao mesmo tempo.",
         tags="#carloacutis #santodosmillennials #eucaristia #catolico #fecatolica #jovenscatolicos #santoscatolicos",
         photo="Foto oficial de Carlo Acutis (amplamente divulgada pela Igreja para sua canonização) — busque “Carlo Acutis” no Wikimedia Commons."),
    dict(n=11, cat="santos", hook="Por que rezamos a Santo Antônio pra achar coisas perdidas?",
         fact="A tradição vem de uma lenda: um noviço fugiu do convento levando o livro de orações de Santo Antônio. O santo rezou para que fosse devolvido — e o rapaz, arrependido, voltou com o livro. Desde então, virou o “padroeiro dos perdidos e achados”.",
         caption="“Santo Antônio, Santo Antônio, cadê minhas chaves?” \U0001F511 Você sabe de onde vem essa tradição?\n\nReza a lenda que um noviço fugiu levando o livro de orações do próprio Santo Antônio — e ele rezou tanto que o rapaz voltou, arrependido, com o livro embaixo do braço.\n\nDesde então, ele é o santo que a gente chama quando perde alguma coisa (ou alguém).",
         tags="#santoantonio #santoantoniodepadua #santoscatolicos #catolico #fecatolica #devocaopopular",
         photo="Imagem de Santo Antônio de Pádua com o Menino Jesus e um lírio — busque “Saint Anthony of Padua” no Wikimedia Commons."),

    dict(n=12, cat="padres", hook="O celibato dos padres não é tão antigo quanto parece",
         fact="A obrigatoriedade do celibato para padres do rito latino só foi formalizada no Segundo Concílio de Latrão, em 1139. Antes disso, era comum — mas não uma regra universal.",
         caption="O celibato sacerdotal como regra formal tem “só” quase 900 anos — bem menos do que muita gente imagina. \U0001F4DC\n\nEle foi oficializado no Segundo Concílio de Latrão, em 1139, embora já fosse um costume valorizado bem antes disso.\n\nHistória da Igreja tem sempre uma camada a mais do que parece à primeira vista.",
         tags="#historiadaigreja #padrescatolicos #celibato #igrejacatolica #catolico #fecatolica #vidasacerdotal",
         photo="Ordenação sacerdotal (imposição das mãos pelo bispo) — busque “Catholic priest ordination” no Wikimedia Commons."),
    dict(n=13, cat="padres", hook="Nem todo padre católico é celibatário",
         fact="Padres de ritos orientais católicos (como o bizantino) podem, sim, ser casados — desde que o casamento aconteça antes da ordenação sacerdotal.",
         caption="Plot twist: existem padres católicos casados. \U0001F48D\n\nNos ritos orientais católicos (bizantino, siro-malabar, entre outros), homens casados podem ser ordenados padres — desde que o casamento tenha vindo antes da ordenação.\n\nA Igreja Católica é uma família bem mais diversa do que a gente costuma aprender.",
         tags="#igrejacatolica #ritooriental #padrescatolicos #historiadaigreja #catolico #fecatolica",
         photo="Padre de rito oriental católico com família — busque “Eastern Catholic priest married clergy” no Wikimedia Commons."),
    dict(n=14, cat="padres", hook="Por que chamamos o padre de “padre”?",
         fact="A palavra vem direto do latim “pater”, que significa “pai” — reforçando a ideia do sacerdote como pai espiritual da comunidade que ele serve.",
         caption="Você já parou pra pensar por que chamamos o padre de... padre? \U0001F468‍\U0001F466\n\nA palavra vem do latim “pater” — pai. Não à toa: o papel dele na comunidade é justamente o de um pai espiritual, que orienta, cuida e caminha junto.\n\nManda esse post pro padre da sua paróquia como agradecimento. \U0001F64F",
         tags="#padrescatolicos #vidasacerdotal #catolico #fecatolica #igrejacatolica #paroquia",
         photo="Padre conversando/acolhendo fiéis na saída da missa — busque “Catholic priest parish community” no Unsplash."),
    dict(n=15, cat="padres", hook="O padre que confessava até 16 horas por dia",
         fact="São João Maria Vianney, o Cura d'Ars, é o padroeiro dos padres — e ficou famoso por passar até 16 horas por dia no confessionário, atendendo peregrinos que vinham de toda a França.",
         caption="O padroeiro dos padres tinha uma rotina que parece impossível hoje em dia. ⏳\n\nSão João Maria Vianney, o Cura d'Ars, chegava a confessar 16 horas por dia — peregrinos vinham de toda a França só pra se confessar com ele.\n\nUm lembrete bonito do peso (e do dom) que é o sacramento da confissão.",
         tags="#saojoaomariavianney #curadars #padrescatolicos #confissao #catolico #fecatolica #santoscatolicos",
         photo="Imagem/estátua de São João Maria Vianney, o Cura d'Ars — busque “Saint John Vianney” no Wikimedia Commons."),

    dict(n=16, cat="historia", hook="A Bíblia católica tem 7 livros a mais que a maioria das protestantes",
         fact="A Bíblia católica reconhece 73 livros — 46 no Antigo Testamento e 27 no Novo. A diferença de 7 livros no Antigo Testamento (os deuterocanônicos) vem de decisões editoriais tomadas séculos depois da formação do cânon católico.",
         caption="Sabia que existe mais de uma “versão” de quantos livros tem a Bíblia? \U0001F4D6\n\nA Bíblia católica tem 73 livros. A maioria das Bíblias protestantes tem 66 — sem os chamados livros deuterocanônicos, como Tobias, Judite e Macabeus.\n\nQual desses 7 você já leu? Comenta aí embaixo.",
         tags="#biblia #canonbiblico #deuterocanonicos #catolico #fecatolica #historiadaigreja #compendiocatolico",
         photo="Bíblia antiga aberta ou manuscrito bíblico iluminado — busque “illuminated Bible manuscript” no Wikimedia Commons."),
    dict(n=17, cat="historia", hook="O Credo que você reza todo domingo nasceu de uma briga teológica",
         fact="O Concílio de Niceia (325 d.C.), o primeiro concílio ecumênico da história, foi convocado pra combater a heresia ariana — e resultou no Credo Niceno, que a Igreja reza até hoje.",
         caption="Aquele Credo que a gente reza (quase no automático) todo domingo tem 1700 anos de história por trás. ⛪\n\nEle nasceu no Concílio de Niceia, em 325 d.C., convocado pra resolver uma das maiores crises teológicas da história da Igreja: a heresia ariana, que negava a divindade plena de Jesus.\n\nDa próxima vez que rezar o Credo, lembra que cada palavra ali foi motivo de debate — e de fé defendida.",
         tags="#conciliodeniceia #credo #historiadaigreja #catolico #fecatolica #teologia #igrejacatolica",
         photo="Pintura/afresco representando o Concílio de Niceia — busque “Council of Nicaea painting” no Wikimedia Commons."),
    dict(n=18, cat="historia", hook="O Vaticano é menor que a maioria dos bairros das grandes cidades",
         fact="Com menos de 0,5 km², o Vaticano é oficialmente o menor país do mundo — e ainda assim é o centro espiritual de mais de 1 bilhão de católicos ao redor do planeta.",
         caption="O menor país do mundo também é, de longe, um dos mais influentes. \U0001F1FB\U0001F1E6\n\nO Vaticano tem menos de meio quilômetro quadrado — mais ou menos o tamanho de um bairro pequeno — mas é o coração espiritual de mais de 1 bilhão de católicos.\n\nTamanho não é documento.",
         tags="#vaticano #cidadedovaticano #papa #catolico #fecatolica #igrejacatolica #curiosidades",
         photo="Vista aérea da Praça e Basílica de São Pedro — busque “Vatican City aerial view” no Wikimedia Commons."),
    dict(n=19, cat="historia", hook="Michelangelo pintou a Sistina praticamente sozinho, por 4 anos",
         fact="Entre 1508 e 1512, Michelangelo pintou praticamente sozinho o teto da Capela Sistina, trabalhando em pé sobre andaimes e com o pescoço curvado pra trás.",
         caption="Um dos maiores tetos da história da arte foi pintado por um homem só, praticamente sozinho, durante 4 anos. \U0001F3A8\n\nMichelangelo pintou o teto da Capela Sistina entre 1508 e 1512, em posições extremamente desconfortáveis, no alto de andaimes.\n\nCada vez que você vê essas imagens, está vendo o resultado de anos de esforço físico e espiritual.",
         tags="#capelasistina #michelangelo #vaticano #artesacra #catolico #fecatolica #historiadaigreja",
         photo="Teto da Capela Sistina (detalhe da Criação de Adão) — busque “Sistine Chapel ceiling” no Wikimedia Commons."),
    dict(n=20, cat="historia", hook="Só dois papas renunciaram voluntariamente em quase 2 mil anos",
         fact="Em 2013, Bento XVI renunciou ao papado — algo que só tinha acontecido de forma clara e voluntária uma vez antes, com o Papa Celestino V, em 1294, quase 720 anos antes.",
         caption="Em quase 2 mil anos de história, só dois papas renunciaram voluntariamente ao cargo. \U0001F4DC\n\nCelestino V, em 1294. E Bento XVI, em 2013 — 719 anos depois.\n\nUma decisão rara, cercada de debate teológico e histórico até hoje.",
         tags="#bentoxvi #papa #vaticano #historiadaigreja #catolico #fecatolica #igrejacatolica",
         photo="Foto oficial do Papa Bento XVI ou do Papa Celestino V em obra de arte — busque “Pope Benedict XVI” no Wikimedia Commons."),
    dict(n=21, cat="historia", hook="A palavra “quarentena” nasceu de uma prática cristã medieval",
         fact="O termo vem do italiano “quaranta giorni” (quarenta dias) — o período em que viajantes eram isolados em portos durante epidemias, um número inspirado em referências bíblicas como o dilúvio e o jejum de Jesus no deserto.",
         caption="Se você usou a palavra “quarentena” em 2020, sem saber, estava citando uma tradição bíblica. \U0001F30A\n\nO termo vem do italiano “quaranta giorni” — 40 dias —, período de isolamento usado em portos durante epidemias na Idade Média. O número 40 remete direto ao dilúvio e ao jejum de Jesus no deserto.\n\nA fé deixou marcas até no nosso vocabulário do dia a dia.",
         tags="#curiosidadeshistoricas #historiadaigreja #biblia #catolico #fecatolica #idademedia",
         photo="Porto medieval ou pintura do dilúvio/arca de Noé — busque “medieval quarantine port” ou “Noah's Ark painting” no Wikimedia Commons."),
    dict(n=22, cat="historia", hook="As universidades mais antigas do mundo nasceram dentro da Igreja",
         fact="Universidades como Bolonha, Paris e Oxford, entre as mais antigas do mundo ocidental, surgiram ligadas a mosteiros e catedrais católicas, num sistema criado pra formar clérigos e preservar o conhecimento.",
         caption="A universidade como você conhece hoje nasceu dentro de mosteiros e catedrais católicas. \U0001F393\n\nBolonha (1088), Paris e Oxford estão entre as mais antigas do mundo — todas com raízes diretas na estrutura educacional da Igreja medieval.\n\nA Igreja não só preservou conhecimento na Idade Média: ela literalmente inventou o modelo de universidade.",
         tags="#historiadaigreja #idademedia #universidade #catolico #fecatolica #curiosidadeshistoricas",
         photo="Universidade de Bolonha ou claustro de mosteiro medieval — busque “University of Bologna medieval” no Wikimedia Commons."),

    dict(n=23, cat="chosen", hook="A primeira série sobre Jesus financiada pelos próprios fãs",
         fact="The Chosen foi majoritariamente financiada por crowdfunding — os criadores arrecadaram milhões de dólares de apoiadores antes mesmo de gravar boa parte da série, um modelo inédito pra uma produção desse tamanho.",
         caption="Uma das maiores produções já feitas sobre a vida de Jesus não veio de um grande estúdio de Hollywood — veio de quem assiste. \U0001F3AC\n\n“The Chosen” foi financiada majoritariamente por crowdfunding, com fãs bancando temporada após temporada.\n\nJá assistiu? Conta aqui qual foi sua cena favorita.",
         tags="#thechosen #jesus #seriecrista #fecatolica #catolico #crowdfunding #biblia",
         photo="Repost de post/story oficial de @thechosen (com crédito) ou imagem do kit de imprensa da Angel Studios — nunca capturas de tela próprias da série."),
    dict(n=24, cat="chosen", hook="O ator que faz Jesus reza antes de cada cena",
         fact="Jonathan Roumie, que interpreta Jesus em The Chosen, já contou em entrevistas que ora antes das gravações e que, em algumas cenas mais intensas, se emociona genuinamente sem planejar.",
         caption="Jonathan Roumie, o ator por trás do Jesus de “The Chosen”, trata o papel com um cuidado espiritual raro em Hollywood. \U0001F64F\n\nEle já contou que reza antes das cenas — e que, em alguns momentos mais fortes, chega a se emocionar de verdade, sem ensaiar.\n\nInterpretar Jesus, pra ele, virou também uma jornada de fé pessoal.",
         tags="#thechosen #jonathanroumie #jesus #seriecrista #catolico #fecatolica #atores",
         photo="Repost de entrevista/post oficial de Jonathan Roumie ou @thechosen com crédito — evite frames extraídos da série."),
    dict(n=25, cat="chosen", hook="O criador de The Chosen quase desistiu do cinema antes da série",
         fact="Dallas Jenkins, diretor e criador da série, teve um filme anterior que fracassou tanto comercialmente que ele pensou seriamente em abandonar a carreira — pouco antes de criar o maior projeto crowdfunded sobre a vida de Jesus.",
         caption="Antes do maior sucesso da carreira, veio o maior fracasso. \U0001F3A5\n\nDallas Jenkins, criador de “The Chosen”, teve um filme anterior que quebrou tanto que ele pensou em largar o cinema de vez.\n\nPouco depois, criou a série sobre Jesus mais vista da história do streaming religioso. Às vezes o “não” vem antes do maior “sim”.",
         tags="#thechosen #dallasjenkins #jesus #seriecrista #fecatolica #catolico #superacao",
         photo="Repost de entrevista/post oficial da produção ou foto de bastidores liberada pela Angel Studios, sempre com crédito."),
    dict(n=26, cat="chosen", hook="Os atores falam hebraico, aramaico e latim em cena",
         fact="Pra dar mais realismo histórico, The Chosen inclui diálogos e trechos em hebraico, aramaico e latim — os idiomas realmente falados na Judeia do século I.",
         caption="Um detalhe que mostra o cuidado histórico de “The Chosen”: os atores falam trechos em hebraico, aramaico e latim, os idiomas reais da época de Jesus. \U0001F5E3️\n\nNão é só drama bíblico — é também uma tentativa séria de reconstruir o contexto histórico e cultural da Judeia do século I.\n\nJá reparou nesses momentos assistindo?",
         tags="#thechosen #hebraico #aramaico #jesus #seriecrista #catolico #fecatolica #historiabiblica",
         photo="Repost de cena/post oficial da produção com crédito — ou, alternativamente, mapa/imagem da Judeia no século I (domínio público)."),
    dict(n=27, cat="chosen", hook="A equipe reza antes de gravar as cenas mais fortes",
         fact="Segundo relatos da própria produção, o elenco e a equipe técnica de The Chosen fazem orações antes de gravar cenas de forte peso espiritual, como a Última Ceia e a crucificação.",
         caption="Antes de gravar as cenas mais pesadas — como a Última Ceia e a crucificação — a equipe de “The Chosen” para tudo pra rezar junto. \U0001F54A️\n\nUm cuidado que vai além da produção: é tratar aquelas cenas com o peso espiritual que elas realmente têm pra milhões de pessoas.\n\nIsso muda como você assiste a série?",
         tags="#thechosen #ultimaceia #crucificacao #jesus #seriecrista #catolico #fecatolica",
         photo="Repost de post oficial da produção sobre bastidores de oração, com crédito — evite reproduzir cenas da crucificação sem autorização."),
    dict(n=28, cat="chosen", hook="The Chosen já foi assistida em quase todos os países do mundo",
         fact="A série já foi dublada e legendada em mais de 50 idiomas, alcançando espectadores em praticamente todos os continentes — um feito raro pra uma produção sobre temas religiosos.",
         caption="“The Chosen” ultrapassou fronteiras que poucas séries religiosas já cruzaram. \U0001F30E\n\nJá foi dublada e legendada em mais de 50 idiomas, chegando a espectadores em quase todos os países do mundo.\n\nA vida de Jesus contada em série, falando literalmente todas as línguas.",
         tags="#thechosen #jesus #seriecrista #fecatolica #catolico #evangelizacao #missao",
         photo="Repost de post/mapa oficial de alcance global da produção (@thechosen), com crédito."),
    dict(n=29, cat="chosen", hook="O ator de São Pedro é judeu israelense — e o papel mudou sua visão sobre Jesus",
         fact="Shahar Isaac, ator israelense que interpreta São Pedro na série, já declarou em entrevistas que viver o papel mudou a forma como ele enxerga a figura de Jesus, mesmo sem ser cristão.",
         caption="Um dos bastidores mais bonitos de “The Chosen”: o ator que interpreta São Pedro é judeu israelense — e o papel mudou a forma como ele enxerga Jesus. ✡️✝️\n\nShahar Isaac já contou em entrevistas o quanto viver esse personagem, mesmo sem ser cristão, foi uma experiência transformadora.\n\nÀs vezes a fé alcança a gente pelos caminhos mais inesperados.",
         tags="#thechosen #saopedro #shaharisaac #jesus #seriecrista #catolico #fecatolica",
         photo="Repost de entrevista/post oficial de Shahar Isaac ou @thechosen, com crédito."),
    dict(n=30, cat="chosen", hook="A série mostra o que a Bíblia não conta em detalhes",
         fact="Boa parte de The Chosen retrata momentos “invisíveis” dos Evangelhos — o dia a dia dos apóstolos antes de seguir Jesus, suas dúvidas, suas famílias — preenchendo, com respeito ao texto bíblico, lacunas que a Bíblia não detalha.",
         caption="Uma das razões de “The Chosen” conquistar tanta gente: ela mostra os “bastidores” que a Bíblia não detalha. \U0001F4D6\n\nO dia a dia dos apóstolos antes de seguir Jesus, suas dúvidas, suas famílias — tudo isso construído com respeito ao que os Evangelhos realmente dizem.\n\nQual apóstolo te surpreendeu mais na série? Comenta aqui embaixo. \U0001F447",
         tags="#thechosen #apostolos #evangelhos #jesus #seriecrista #catolico #fecatolica #biblia",
         photo="Repost de post oficial da produção sobre os apóstolos, com crédito — ou ilustração/pintura clássica dos apóstolos em domínio público."),

    dict(n=31, cat="mundo", hook="Cristiano Ronaldo carrega a fé de Fátima pra dentro de campo",
         fact="CR7 nasceu na Madeira, ilha portuguesa profundamente católica, e já visitou o Santuário de Fátima diversas vezes — o filho mais velho e outros familiares foram batizados na fé católica.",
         caption="Nem todo mundo sabe: Cristiano Ronaldo é católico praticante e já visitou Fátima várias vezes ao longo da carreira. ⚽\U0001F64F\n\nCrescer na Madeira, uma das regiões mais católicas de Portugal, deixou marcas — inclusive na forma como ele fala sobre fé e família em entrevistas.\n\nMarca aquele amigo fã de futebol que não sabia dessa!",
         tags="#cristianoronaldo #futebolecatolicismo #catolico #fecatolica #fatima #curiosidades",
         photo="Foto de imprensa/editorial licenciada de Cristiano Ronaldo em Fátima, ou — mais seguro — um card de texto autoral com a curiosidade sobre fundo do Santuário de Fátima (domínio público)."),
    dict(n=32, cat="mundo", hook="O gesto de Messi ao entrar em campo tem um significado religioso",
         fact="Lionel Messi costuma se benzer e olhar para o céu antes das partidas, e carrega uma tatuagem com o rosto de Jesus e outra de Nossa Senhora — reflexo de uma criação católica na cidade de Rosário, Argentina.",
         caption="Aquele gesto de Messi antes de entrar em campo — o sinal da cruz, o olhar pro céu — não é só superstição de jogador. ⚽✝️\n\nEle carrega tatuagens com o rosto de Jesus e de Nossa Senhora, reflexo de uma criação católica em Rosário, na Argentina.\n\nA fé aparece até nos detalhes que a gente vê (mas nem sempre repara) na Copa do Mundo.",
         tags="#messi #futebolecatolicismo #catolico #fecatolica #argentina #curiosidades",
         photo="Foto de imprensa/editorial licenciada de Messi se benzendo em campo, ou card de texto autoral com a curiosidade — evite reproduzir fotos esportivas protegidas sem licença."),
    dict(n=33, cat="mundo", hook="Kobe Bryant foi à missa horas antes de morrer",
         fact="Kobe Bryant se converteu ao catolicismo ao se casar com Vanessa Bryant e, segundo relatos amplamente divulgados na imprensa, participou da missa na manhã do dia do acidente que o vitimou, em janeiro de 2020.",
         caption="Uma curiosidade que emocionou muita gente na época: Kobe Bryant, que havia se convertido ao catolicismo, foi à missa na manhã do dia em que morreu, em 2020. \U0001F54A️\U0001F3C0\n\nUm lembrete silencioso de como a fé estava presente no dia a dia dele, longe das quadras.\n\nDescanse em paz, Kobe.",
         tags="#kobebryant #catolico #fecatolica #basquete #curiosidades #fe",
         photo="Foto de imprensa/editorial licenciada de Kobe Bryant, ou — mais seguro — card de texto autoral com a curiosidade sobre fundo neutro/quadra de basquete genérica."),
    dict(n=34, cat="mundo", hook="O tenor que já cantou pra três papas diferentes",
         fact="Andrea Bocelli, um dos tenores mais famosos do mundo, é católico praticante e já se apresentou em eventos oficiais do Vaticano para mais de um pontificado, incluindo apresentações do “Ave Maria”.",
         caption="A voz de Andrea Bocelli já ecoou dentro do Vaticano — pra mais de um Papa. \U0001F3B6✝️\n\nCatólico praticante, ele já cantou o “Ave Maria” em eventos oficiais da Igreja, unindo música clássica e fé de um jeito raro na indústria da música.\n\nJá ouviu alguma apresentação dele? Deixa aqui embaixo.",
         tags="#andreabocelli #musicasacra #catolico #fecatolica #vaticano #curiosidades",
         photo="Foto de imprensa/editorial licenciada de Andrea Bocelli em apresentação, ou card de texto autoral com a curiosidade sobre fundo de igreja/basílica (domínio público)."),
    dict(n=35, cat="mundo", hook="O autor de O Senhor dos Anéis era um católico devoto",
         fact="J.R.R. Tolkien, autor de “O Senhor dos Anéis”, era católico praticante e afirmou, em cartas próprias, que a obra é fundamentalmente “uma obra religiosa e católica”, mesmo sem menções diretas à religião no enredo.",
         caption="“O Senhor dos Anéis” tem mais fé católica escondida nas entrelinhas do que parece. \U0001F4DA\U0001F48D\n\nO próprio J.R.R. Tolkien, católico devoto, escreveu em cartas que a obra é “fundamentalmente uma obra religiosa e católica” — só que sem pregação direta, tecida na história.\n\nAgora você vai reler a trilogia com outros olhos.",
         tags="#tolkien #osenhordosaneis #literatura #catolico #fecatolica #curiosidades",
         photo="Capa de edição de O Senhor dos Anéis ou foto de domínio público/editorial licenciada de J.R.R. Tolkien — verifique a licença da capa usada."),
    dict(n=36, cat="mundo", hook="O diretor de Taxi Driver quase virou padre",
         fact="Martin Scorsese, um dos maiores diretores de cinema vivos, estudou num seminário católico quando jovem, pensando em ser padre, antes de seguir carreira no cinema — a fé católica aparece até hoje em filmes como “Silêncio” e “O Irlandês”.",
         caption="Antes de dirigir clássicos como “Taxi Driver” e “Os Bons Companheiros”, Martin Scorsese quase seguiu outro caminho: o sacerdócio. ⛪\U0001F3AC\n\nEle chegou a estudar num seminário católico quando jovem — e a fé nunca saiu de verdade dos filmes dele, principalmente em “Silêncio”, sobre missionários jesuítas no Japão.\n\nJá assistiu “Silêncio”? É daquelas obras que ficam.",
         tags="#martinscorsese #cinemaefe #catolico #fecatolica #silencio #curiosidades",
         photo="Cartaz do filme Silêncio (2016) — verifique direitos de uso da imagem promocional — ou card de texto autoral com a curiosidade."),
    dict(n=37, cat="mundo", hook="Um time de futebol criado por um frade para alimentar crianças pobres",
         fact="O Celtic Football Club, da Escócia, foi fundado em 1887 pelo Irmão Walfrid, um religioso marista, com o objetivo declarado de arrecadar fundos para alimentar crianças pobres de famílias católicas imigrantes em Glasgow.",
         caption="Um dos clubes de futebol mais tradicionais da Europa nasceu de uma obra de caridade católica. ⚽\U0001F340\n\nO Celtic FC foi fundado em 1887 pelo Irmão Walfrid, religioso marista, com um objetivo bem direto: arrecadar dinheiro para alimentar crianças pobres de famílias católicas imigrantes em Glasgow.\n\nFutebol e caridade, juntos desde o primeiro apito.",
         tags="#celticfc #futebolecatolicismo #historiadaigreja #catolico #fecatolica #curiosidades",
         photo="Escudo/brasão do Celtic FC (uso editorial) ou foto histórica do Irmão Walfrid — busque “Brother Walfrid Celtic” no Wikimedia Commons."),
    dict(n=38, cat="mundo", hook="A universidade com um “Jesus” gigante olhando pro estádio",
         fact="A Universidade de Notre Dame, nos EUA, é uma instituição católica fundada em 1842 por padres da Congregação da Santa Cruz — e tem um mural gigante de Jesus de braços erguidos virado justamente para o estádio de futebol americano, apelidado de “Touchdown Jesus”.",
         caption="Existe uma universidade nos EUA onde “Jesus” literalmente assiste aos jogos de futebol americano. ⛪\U0001F3C8\n\nA Universidade de Notre Dame, católica, fundada em 1842 por padres da Congregação da Santa Cruz, tem um mural enorme de Jesus de braços abertos virado pro estádio — apelidado carinhosamente de “Touchdown Jesus”.\n\nFé e tradição esportiva, lado a lado.",
         tags="#notredame #touchdownjesus #universidadecatolica #catolico #fecatolica #curiosidades",
         photo="Mural “Touchdown Jesus” na biblioteca Hesburgh da Universidade de Notre Dame, visto do estádio — busque “Touchdown Jesus Notre Dame” no Wikimedia Commons."),
]
